apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: springboot-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/AgustinRibotta/PetGrooming
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: petapp-main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
