apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: petapp-main
spec:
  selector:
    app: react-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 80   
      nodePort: 30414  
